# Generated by Django 4.2.4 on 2023-09-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('numero_pedido', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('estado_pedido', models.CharField(max_length=10)),
                ('total_pagar_pedido', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
