# Generated by Django 4.2.4 on 2023-09-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aprendiz', '0002_alter_aprendiz_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_ficha',
            field=models.IntegerField(),
        ),
    ]
